# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-10-09 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asientoContable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('importeDebe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('importeHaber', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='cuentaPCGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('detalle', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='libroDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asientoD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asientos_contables.asientoContable')),
            ],
        ),
        migrations.CreateModel(
            name='libroMayor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_folio', models.IntegerField()),
                ('total_debe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_haber', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cuentaM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asientos_contables.cuentaPCGA')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cuentas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asientos_contables.cuentaPCGA'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='cuentas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asientos_contables.cuentaPCGA'),
        ),
    ]
