# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-10-11 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_contables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuentaT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importeDebe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('importeHaber', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='asientocontable',
            name='importeDebe',
        ),
        migrations.RemoveField(
            model_name='asientocontable',
            name='importeHaber',
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='cuentaT',
            field=models.ManyToManyField(to='asientos_contables.cuentaT'),
        ),
    ]
