# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-10-11 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_contables', '0002_auto_20191010_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asientocontable',
            name='cuentaT',
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='importeDebe',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='importeHaber',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='cuentaT',
        ),
    ]
