# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-10-11 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_contables', '0003_auto_20191010_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='cuentas',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='codigo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuenta',
            name='detalle',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='asientocontable',
            name='cuentas',
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='cuentas',
            field=models.ManyToManyField(to='asientos_contables.cuenta'),
        ),
        migrations.AlterField(
            model_name='libromayor',
            name='cuentaM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asientos_contables.cuenta'),
        ),
        migrations.DeleteModel(
            name='cuentaPCGA',
        ),
    ]
