# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-10-11 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_contables', '0005_auto_20191010_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asientocontable',
            name='cuentas',
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='cuentas',
            field=models.ManyToManyField(to='asientos_contables.cuenta'),
        ),
    ]
