# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-10-12 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_contables', '0006_auto_20191010_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asientocontable',
            name='cuentas',
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='cuentas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asientos_contables.cuenta'),
            preserve_default=False,
        ),
    ]
