# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-10-12 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_contables', '0008_auto_20191012_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='detalle',
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='detalle',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
