# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-10-20 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_contables', '0009_auto_20191012_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('haber', models.DecimalField(decimal_places=2, max_digits=8)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asientos_contables.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='registroTMayor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asientos_contables.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='tipoCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='libromayor',
            name='cuentaM',
        ),
        migrations.RenameField(
            model_name='asientocontable',
            old_name='importeDebe',
            new_name='debe',
        ),
        migrations.RenameField(
            model_name='asientocontable',
            old_name='detalle',
            new_name='detalle_debe',
        ),
        migrations.RenameField(
            model_name='asientocontable',
            old_name='importeHaber',
            new_name='haber',
        ),
        migrations.RemoveField(
            model_name='asientocontable',
            name='cuentas',
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='cuenta_debe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_debe', to='asientos_contables.cuenta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='cuenta_haber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_haber', to='asientos_contables.cuenta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='detalle_haber',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='numero_asiento',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='libroMayor',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asientos_contables.registroTMayor'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asientos_contables.tipoCuenta'),
            preserve_default=False,
        ),
    ]
