# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-11-01 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_contables', '0010_auto_20191020_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='balanceComprobacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalSumaDebe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('totalSumaHaber', models.DecimalField(decimal_places=2, max_digits=8)),
                ('totalSaldoDebe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('totalSaldoHaber', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='elementoBalanceComprobacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumaDebe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sumaHaber', models.DecimalField(decimal_places=2, max_digits=8)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asientos_contables.balanceComprobacion')),
                ('cuentas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asientos_contables.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='elementoMayor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('debe', models.DecimalField(decimal_places=3, max_digits=8)),
                ('haber', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='libroDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='libroMayor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asientos_contables.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='libroMayores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mayor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asientos_contables.libroMayor')),
            ],
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='registro',
        ),
        migrations.RemoveField(
            model_name='registrotmayor',
            name='cuenta',
        ),
        migrations.RenameField(
            model_name='asientocontable',
            old_name='debe',
            new_name='importeDebe',
        ),
        migrations.RenameField(
            model_name='asientocontable',
            old_name='haber',
            new_name='importeHaber',
        ),
        migrations.RemoveField(
            model_name='asientocontable',
            name='detalle_debe',
        ),
        migrations.RemoveField(
            model_name='asientocontable',
            name='detalle_haber',
        ),
        migrations.RemoveField(
            model_name='asientocontable',
            name='fecha',
        ),
        migrations.DeleteModel(
            name='movimiento',
        ),
        migrations.DeleteModel(
            name='registroTMayor',
        ),
        migrations.AddField(
            model_name='elementomayor',
            name='mayor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asientos_contables.libroMayor'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='libroD',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asientos_contables.libroDiario'),
            preserve_default=False,
        ),
    ]
