# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-11-04 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_contables', '0011_auto_20191101_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementomayor',
            name='fecha',
        ),
        migrations.AddField(
            model_name='balancecomprobacion',
            name='cuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asientos_contables.cuenta'),
            preserve_default=False,
        ),
    ]
