# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-11-05 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_contables', '0012_auto_20191103_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancecomprobacion',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='balancecomprobacion',
            name='totalSaldoDebe',
        ),
        migrations.RemoveField(
            model_name='balancecomprobacion',
            name='totalSaldoHaber',
        ),
        migrations.RemoveField(
            model_name='elementobalancecomprobacion',
            name='balance',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='subcuenta',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='codigo',
            field=models.CharField(max_length=25),
        ),
    ]
