# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-11-09 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_contables', '0013_auto_20191104_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asientocontable',
            name='numero_asiento',
        ),
    ]
