# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-11-20 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_contables', '0013_auto_20191104_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='periodoContable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaFinal', models.DateField()),
                ('estado', models.CharField(default='Abierto', max_length=25)),
            ],
        ),
    ]
