# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-11-20 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_contables', '0014_periodocontable'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asientos_contables.periodoContable'),
        ),
    ]
