# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-11-10 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_contables', '0014_remove_asientocontable_numero_asiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='numero_asiento',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
