# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-11-22 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_contables', '0015_asientocontable_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementomayor',
            name='periodoCont',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asientos_contables.periodoContable'),
        ),
    ]
