# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-11-23 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asientos_contables', '0016_elementomayor_periodocont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='subcuenta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
