# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-11-13 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCargo', models.CharField(blank=True, max_length=100, null=True)),
                ('gerencia', models.CharField(blank=True, choices=[('TI', 'ti'), ('Ventas', 'vt'), ('Contabilidad', 'cb'), ('Operciones', 'op')], max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaContratacion', models.DateField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cargo', to='Planilla.Cargo')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('dui', models.CharField(blank=True, max_length=10, null=True)),
                ('nit', models.CharField(blank=True, max_length=18, null=True)),
                ('nup', models.CharField(blank=True, max_length=20, null=True)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('isss', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haberBase', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Haber Base')),
                ('porcISSS', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Porcentaje descuento ISSS')),
                ('porcAFP', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Porcentaje descuento AFP')),
                ('bonoAntig', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Bono de Antiguedad')),
                ('horasExtra', models.IntegerField(verbose_name='Nº Horas Extra')),
                ('montoHorasExtra', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto por Horas Extra')),
                ('bonoProduccion', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Bono por Produccion')),
                ('otrosBonos', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Otros Bonos')),
                ('sueldoNeto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Sueldo Neto')),
                ('sueldoBruto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Sueldo Bruto')),
                ('otrosDescuentos', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Otros Descuentos')),
            ],
            options={
                'verbose_name': 'Salario',
                'verbose_name_plural': 'Salarios',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empleado', to='Planilla.Empleado'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='salario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Salario', to='Planilla.Salario'),
        ),
    ]
