# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-11-23 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Planilla', '0003_auto_20191119_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horasExtra', models.IntegerField(blank=True, null=True, verbose_name='Nº Horas Extra')),
                ('montoHorasExtra', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Monto por Horas Extra')),
                ('bonoProduccion', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bono por Produccion')),
                ('otrosBonos', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Otros Bonos')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('anyo', models.IntegerField(verbose_name='Año')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='Planilla.Contrato')),
            ],
            options={
                'verbose_name': 'Detalle de Mes',
                'verbose_name_plural': 'Destalles de Mes',
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('anyo', models.IntegerField(verbose_name='Año')),
                ('total_salarios', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total de Salarios')),
                ('total_renta', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total de Retencion de Renta')),
                ('total_afp', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total de AFP')),
                ('total_isss', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total de ISSS')),
                ('contrato', models.ManyToManyField(to='Planilla.Contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Planilla',
                'verbose_name_plural': 'Planillas',
            },
        ),
        migrations.RemoveField(
            model_name='salario',
            name='bonoProduccion',
        ),
        migrations.RemoveField(
            model_name='salario',
            name='horasExtra',
        ),
        migrations.RemoveField(
            model_name='salario',
            name='montoHorasExtra',
        ),
        migrations.RemoveField(
            model_name='salario',
            name='otrosBonos',
        ),
    ]
